### PR TITLE
[ADD] VNode: add support for classes as predicates

### PR DESCRIPTION
**Pull request by dmo-odoo**

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@Zinston I suggest you to try this commit on your list branch.
By writing your `instanceof` predicates like the following:
```
export function isList(node: VNode): node is ListNode {
    return node instanceof ListNode;
}
```
Typescript will now recognize that the return value of `node.next(isList)` is a `ListNode`, not merely a `VNode`, thus removing the need to manually do `as ListNode` on the result.

**Comment by dmo-odoo** [comment]
@Zinston Even better. I just added a magic `is` to the `Predicates` utils which creates type guards from classes. You don't even need to manually create a predicate to use type guards on classes that extends VNode.
Example:
```
const list: ListNode = item.ancestor(is(ListNode));
```

**Comment by dmo-odoo** [comment]
@Zinston Retrospectively, I'm not sure that `is` method is very useful. It's not hard to write a proper type guard and at least that function will only be defined once, where `is` will generate a brand new function everytime we reach that point in the code...

**Comment by dmo-odoo** [comment]
@Zinston Remember a few hours ago when I told you I tried and it couldn't be done ? Well, it turns out I just did it.

**Comment by Zinston** [comment]
> @Zinston Remember a few hours ago when I told you I tried and it couldn't be done ? Well, it turns out I just did it.

image

**Comment by Zinston** [comment]
> > @Zinston Remember a few hours ago when I told you I tried and it couldn't be done ? Well, it turns out I just did it.
> 
> image

Also: 
image

**Pull request merged**
