### PR TITLE
[FIX] allow the main zone stretch vertically

### PR DESCRIPTION
**Pull request by Goaman**

### CODE REVIEW

**Comment by dmo-odoo** [comment]
@Goaman : change the commit message to `[FIX] OdooWebsiteEditor: allow the main zone stretch vertically` and I merge it.

**Comment by dmo-odoo** [comment]
@Goaman You force-pushed the branch but did not fix the commit message.

**Comment by Goaman** [comment]
done

**Comment by dmo-odoo** [comment]
Renaming: failed.

**Comment by Goaman** [comment]
^^`

**Pull request merged**
