### PR TITLE
Master fix selection without root nby

### PR DESCRIPTION
**Pull request by Goaman**

### CODE REVIEW

**Comment by Goaman** [comment]
I need something like this for the integration

**Comment by dmo-odoo** [comment]
@Goaman Does this still apply with the new layout ?

**Comment by dmo-odoo** [comment]
@Goaman ping

**Comment by Goaman** [comment]
Indeed, the problem has disappeared in master.
But the test might still be relevant.

**Comment by dmo-odoo** [comment]
Then if the PR is modified to only contain the test then I could merge it.

**Comment by Goaman** [comment]
done

**Pull request merged**
